services:
#    api.example:
#        class: ApiBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    domain.device.create_new_device:
        class: ApiBundle\Domain\Device\CreateNewDevice
        arguments: [!tagged onCreateNewDevice]

    action.send_mail_on_create_new_device:
        class: ApiBundle\Services\Actions\SendMailOnCreateNewDevice
        arguments: ['%mailToApprovalDevice%']
        tags: ['onCreateNewDevice']