<?php

namespace ApiBundle\Repository;

use ApiBundle\Entity\Device;
use Doctrine\ORM\EntityRepository;

/**
 * DeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviceRepository extends EntityRepository
{
    public function save(Device $entity)
    {
        $this->_em->persist($entity);
        $this->_em->flush();
    }

    public function update(Device $entity)
    {
        $this->_em->merge($entity);
        $this->_em->flush();
    }

    public function remove(Device $entity)
    {
        $this->_em->remove($entity);
        $this->_em->flush();
    }

    public function getAllAcceptedDevices()
    {
        return $this->findBy(['accepted' => 1]);
    }
}
